#pragma config(Sensor, in1,    intakeSensor,   sensorReflection)
#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftButton,     sensorTouch)
#pragma config(Sensor, dgtl2,  catButton,      sensorTouch)
#pragma config(Motor,  port1,           rLift,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           bl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           br,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           fr,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           fl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rFlip,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           lFlip,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rCat,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void setIntake(int value){
	motor[lFlip]=value;
	motor[rFlip]=value;
}
void liftUp(){
	while(SensorValue[intakeSensor]>800)
	{
		setIntake(-50);
	}
	setIntake(-10);
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
  while (1)
  {
  if (SensorValue[liftButton]==1)
  {
  		motor[rLift]=(vexRT[Btn5U]-vexRT[Btn5D])*127-15;
	motor[lLift]=(vexRT[Btn5U]-vexRT[Btn5D])*127-15;
}
else
{
	motor[rLift]=(vexRT[Btn5U]-vexRT[Btn5D])*127+15;
	motor[lLift]=(vexRT[Btn5U]-vexRT[Btn5D])*127+15;
}

	motor[bl]=vexRT[Ch3];
	motor[fl]=-vexRT[Ch3];
	motor[br]=vexRT[Ch2];
	motor[fr]=vexRT[Ch2];

	if(vexRT[Btn6U]==1&&vexRT[Btn6D]==1)setIntake(10);
	else if(SensorValue[liftButton]==1) setIntake((vexRT[Btn6U]-vexRT[Btn6D])*127+10);
	else if(SensorValue[liftButton]==0 && SensorValue[intakeSensor]>800) liftUp();
	else setIntake((vexRT[Btn6U]-vexRT[Btn6D])*127 - 12);



	if(SensorValue[catButton]==1) motor[rCat]=(vexRT[Btn8U]-vexRT[Btn8D])*127+20;
	else motor[rCat]=127;

	}
}
